import InternalRoute from '../server/InternalRoute';

/**
 * This holds the internal route mappings. It's defined by a script tag generated by the back end.
 */
declare var CHROME_VS_CODE_INTERNAL_ROUTE_MAP: Map<InternalRoute, string>;

/**
 * Returns the path to an internal route.
 * @param route The internal route to get the path to.
 */
export default function get(route: InternalRoute): string {
	return CHROME_VS_CODE_INTERNAL_ROUTE_MAP.get(route);
}
